#include <filesystem>

namespace TestUtil {
	/**
	* Generated by CMake; get the path to the TestFiles directory under 'tests'
	*/
	std::filesystem::path getTestFilesDirectory() {
		return "/home/simon/code/cpp/tolc/tests/TestFiles";
	}
}
