site_name: tolc
site_description: 'tolc: Making C++ reusable from other languages'
site_author: 'Simon Rydell'
site_url: 'https://srydell.github.io/tolc/'
strict: true
nav:
  - Introduction: 'index.md'
  - Installing: 'getting_tolc.md'
  - Usage: 'usage.md'
  - Tutorials:
    - Translating a C++ library: 'translating_an_existing_library.md'
  - Signup: 'signup.md'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
theme:
  name: material
  logo: assets/tolc-symbol-color-RGB.png
  favicon: assets/tolc-symbol-color-RGB.png
  font:
    text: IBM Plex
    code: IBM Plex mono
  palette:
    primary: black
    accent: deep purple
extra:
  generator: false
