site_name: tolc
site_description: 'tolc: Making C++ reusable from other languages'
site_author: 'Simon Rydell'
site_url: 'https://srydell.github.io/tolc/'
strict: true
nav:
  - Introduction: 'index.md'
  - Installing: 'getting_tolc.md'
  - Usage: 'usage.md'
  - Guides:
    - Translating a C++ library: 'guides/translating_a_cpp_library.md'
  - CMake:
    - Interface: 'cmake/interface.md'
  - Python:
    - Introduction: 'python/introduction.md'
    - Conversions: 'python/conversions.md'
    - Template Naming Convention: 'python/template_naming_convention.md'
  - FAQ: 'python/FAQ.md'
  - Signup: 'signup.md'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
theme:
  name: null
  custom_dir: 'tolc_theme'
extra:
  generator: false
