site_name: tolc
site_description: 'tolc: Making C++ reusable from other languages'
site_author: 'Simon Rydell'
site_url: 'https://Tolc-Software.github.io/tolc/'
strict: true
nav:
  - Introduction: 'index.md'
  - Installing: 'installing.md'
  - Usage: 'usage.md'
  - Guides:
    - Translating a C++ library: 'guides/translating_a_cpp_library.md'
  - CMake:
    - Interface: 'cmake/interface.md'
    - Reference: 'cmake/reference.md'
  - Python Interface:
    - Introduction: 'python/introduction.md'
    - Conversions: 'python/conversions.md'
    - Template Naming Convention: 'python/template_naming_convention.md'
  - FAQ: 'FAQ.md'
markdown_extensions:
  - fenced_code
theme:
  name: null
  custom_dir: 'tolc_theme'
extra:
  generator: false
