site_name: tolc
site_description: 'tolc: Making C++ reusable from other languages'
site_author: 'Simon Rydell'
site_url: 'https://Tolc-Software.github.io/tolc/'
strict: true
nav:
  - Introduction: 'index.md'
  - Installing: 'installing.md'
  - Usage: 'usage.md'
  - Python Interface:
    - Quickstart: 'python/quickstart.md'
    - Examples: 'python/examples.md'
    - Conversions: 'python/conversions.md'
    - Template Naming Convention: 'python/template_naming_convention.md'
  - WebAssembly Interface:
    - Quickstart: 'webassembly/quickstart.md'
    - Examples: 'webassembly/examples.md'
    - Conversions: 'webassembly/conversions.md'
  - Objective-C Interface:
    - Quickstart: 'objc/quickstart.md'
    - Examples: 'objc/examples.md'
    - Conversions: 'objc/conversions.md'
    - Naming Convention: 'objc/naming_convention.md'
  - CMake:
    - Interface: 'cmake/interface.md'
    - Reference: 'cmake/reference.md'
  - FAQ: 'FAQ.md'
markdown_extensions:
  - fenced_code
theme:
  name: null
  custom_dir: 'tolc_theme'
extra:
  generator: false
