name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2022
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    env:
      VCVARS: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Python cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-refreshed-at-20200621-1
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Download python dependencies
      run: |
        python -m pip install setuptools wheel
        python -m pip install conan ninja

    - name: Conan cache
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key: ${{ runner.os }}-conan-refreshed-at-20200716
        restore-keys: |
          ${{ runner.os }}-conan-

    - name: Configure
      shell: cmd
      run: |
        call "%VCVARS%"
        cmake -S. -Bbuild -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DENABLE_TESTING=ON -DENABLE_PACKAGING=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_FILE_NAME=tolc -G Ninja

    - name: Build
      shell: cmd
      run: |
        call "%VCVARS%"
        cmake --build build -j4

    - name: Run tests
      shell: cmd
      run: |
        call "%VCVARS%"
        cd build
        ctest --output-on-failure -j4

    - name: Build the release tar.xz package
      if: github.ref == 'refs/heads/main'
      shell: cmd
      run: |
        call "%VCVARS%"
        cpack -G TXZ --config build/CPackConfig.cmake

    - name: Push release
      if: github.ref == 'refs/heads/main'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        # Move to keep the directory on Github Actions free from filename clashes
        mv tolc.tar.xz tolc-Windows.tar.xz

        echo "Pushing to the latest tag"
        gh release create latest --title "Latest release from main" --notes "This release gets updated on each commit to main" || true
        gh release upload latest tolc-Windows.tar.xz --clobber

        echo "Making sure the release ${version} is online"
        version="$(cat docs/ReleaseNotes/version)"
        test -f docs/ReleaseNotes/${version}.md
        gh release create "${version}" --title "${version}" --notes-file "docs/ReleaseNotes/${version}.md" || true
        gh release upload "${version}" tolc-Windows.tar.xz || true

